#!/bin/bash
# deploy-pxehost.sh
# Deploys a PXE/DHCP server VM on a KVM host running AlmaLinux 9.
# Must run as root on the KVM host.
# Requires: libvirt, virt-install, nmcli, iproute2

set -euo pipefail

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------
VM_NAME="pxehost"
VM_VCPUS=2
VM_RAM_MB=4096
VM_DISK_GB=20
VM_DISK_PATH="/var/lib/libvirt/images/${VM_NAME}.qcow2"

SUBNET="10.0.0"
GATEWAY="10.0.0.138"
DNS="1.1.1.1"
NETMASK="255.255.255.0"
PREFIX=24

ALMA_ISO_URL="https://repo.almalinux.org/almalinux/9/isos/x86_64/AlmaLinux-9-latest-x86_64-boot.iso"
ALMA_ISO_PATH="/var/lib/libvirt/images/AlmaLinux-9-latest-x86_64-boot.iso"
ALMA_INST_REPO="https://repo.almalinux.org/almalinux/9/BaseOS/x86_64/os/"

# Public key for rootbruker00 on both the VM and clients it serves
PUBKEY="ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIL5G39vHZAQFo6BuFfJtIFUR/4DyQtf9KIIy4jJlcBQt gmarselis@molly.vetinst.no"

KS_FILE="/tmp/pxehost-vm.ks"

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------
log() { echo "[$(date '+%H:%M:%S')] $*"; }
die() { echo "ERROR: $*" >&2; exit 1; }

require() {
    for cmd in "$@"; do
        command -v "$cmd" &>/dev/null || die "Required command not found: $cmd"
    done
}

# ---------------------------------------------------------------------------
# Step 1: Detect or create bridge
# ---------------------------------------------------------------------------
find_or_create_bridge() {
    log "Detecting bridge interface..."

    local br
    for br in $(ip -br link show type bridge | awk '{print $1}'); do
        local members
        members=$(ip link show master "$br" 2>/dev/null \
            | grep -v "lo\|virbr\|vnet\|tap\|dummy" \
            | awk '{print $2}' | tr -d ':' | head -1)
        if [[ -n "$members" ]]; then
            log "Found existing bridge: $br (member: $members)"
            BRIDGE="$br"
            return
        fi
    done

    log "No suitable bridge found. Creating one..."

    local nic
    nic=$(ip -br link show \
        | awk '{print $1}' \
        | grep -Ev '^(lo|virbr|vnet|tap|dummy|br-|docker|bond|team)' \
        | head -1)
    [[ -z "$nic" ]] && die "No suitable physical NIC found to bridge"

    log "Bridging physical NIC: $nic"

    nmcli con add type bridge ifname br0 con-name br0 \
        bridge.stp no \
        ipv4.method disabled \
        ipv6.method disabled

    nmcli con add type ethernet ifname "$nic" con-name "br0-member" \
        master br0

    nmcli con up br0
    nmcli con up "br0-member"

    BRIDGE="br0"
    log "Bridge br0 created on $nic"
}

# ---------------------------------------------------------------------------
# Step 2: Find a free IP in the /24
# ---------------------------------------------------------------------------
find_free_ip() {
    log "Scanning ${SUBNET}.0/${PREFIX} for a free IP starting at .2..."
    local i
    for i in $(seq 2 254); do
        local ip="${SUBNET}.${i}"
        if ! ping -c1 -W1 "$ip" &>/dev/null; then
            log "Free IP found: $ip"
            VM_IP="$ip"
            return
        fi
    done
    die "No free IP found in ${SUBNET}.0/${PREFIX}"
}

# ---------------------------------------------------------------------------
# Step 3: Download AlmaLinux boot ISO if not present
# ---------------------------------------------------------------------------
fetch_iso() {
    if [[ -f "$ALMA_ISO_PATH" ]]; then
        log "AlmaLinux boot ISO already present at $ALMA_ISO_PATH"
        return
    fi
    log "Downloading AlmaLinux 9 boot ISO..."
    curl -L --progress-bar -o "$ALMA_ISO_PATH" "$ALMA_ISO_URL"
    log "ISO downloaded."
}

# ---------------------------------------------------------------------------
# Step 4: Write VM kickstart to file
# This file is injected directly into the installer initrd by virt-install.
# No HTTP server required.
# ---------------------------------------------------------------------------
write_vm_kickstart() {
    log "Writing VM kickstart to $KS_FILE..."

    # VM_IP is set by find_free_ip - capture it now for use inside heredoc
    local vm_ip="$VM_IP"

    cat > "$KS_FILE" <<KSEOF
# VM kickstart - pxehost
# Generated by deploy-pxehost.sh

text
reboot

url --url="${ALMA_INST_REPO}"

lang en_US.UTF-8
keyboard us
timezone UTC --utc

network --bootproto=static --ip=${vm_ip} --netmask=${NETMASK} --gateway=${GATEWAY} --nameserver=${DNS} --hostname=pxehost --device=eth0 --activate --onboot=yes

zerombr
clearpart --all --initlabel
autopart --type=lvm --nohome

rootpw --lock

user --name=rootbruker00 --groups=wheel --lock
sshkey --username=rootbruker00 "${PUBKEY}"

%packages --ignoremissing
@^minimal-environment
bash-completion
curl
dnsmasq
nginx
grub2-efi-x64
shim-x64
xorriso
firewalld
policycoreutils-python-utils
%end

selinux --enforcing

services --enabled=dnsmasq,nginx,firewalld

%post --log=/root/ks-post.log
set -x

# sudoers
cat > /etc/sudoers.d/rootbruker00 <<'EOF'
rootbruker00 ALL=(ALL) NOPASSWD: ALL
EOF
chmod 0440 /etc/sudoers.d/rootbruker00

# TFTP directory tree
TFTPROOT=/srv/tftpboot
mkdir -p \${TFTPROOT}/grub \${TFTPROOT}/images/almalinux9

# Copy EFI binaries into TFTP root
cp /boot/efi/EFI/almalinux/shimx64.efi \${TFTPROOT}/shimx64.efi
cp /boot/efi/EFI/almalinux/grubx64.efi \${TFTPROOT}/grubx64.efi

# Download AlmaLinux 9 boot ISO and extract kernel + initrd
ISO_PATH=/var/cache/pxehost/AlmaLinux-9-latest-x86_64-boot.iso
mkdir -p /var/cache/pxehost
curl -L --progress-bar -o "\${ISO_PATH}" "${ALMA_ISO_URL}"

MNT=\$(mktemp -d)
mount -o loop,ro "\${ISO_PATH}" "\${MNT}"
cp "\${MNT}/images/pxeboot/vmlinuz"    \${TFTPROOT}/images/almalinux9/vmlinuz
cp "\${MNT}/images/pxeboot/initrd.img" \${TFTPROOT}/images/almalinux9/initrd.img
umount "\${MNT}"
rmdir "\${MNT}"

# GRUB menu for PXE clients
cat > \${TFTPROOT}/grub/grub.cfg <<GRUBEOF
set timeout=30
set default=0

menuentry "Install AlmaLinux 9 (kickstart)" {
    linuxefi /images/almalinux9/vmlinuz \\
        inst.repo=${ALMA_INST_REPO} \\
        inst.ks=http://${vm_ip}/kickstart/ks.cfg \\
        ip=dhcp \\
        quiet
    initrdefi /images/almalinux9/initrd.img
}

menuentry "Boot local disk" {
    exit
}
GRUBEOF

# dnsmasq - proxy DHCP + TFTP
cat > /etc/dnsmasq.d/pxe.conf <<DNSEOF
# Proxy DHCP - does not assign IPs, only answers PXE boot requests
dhcp-range=${SUBNET}.0,proxy

# TFTP
enable-tftp
tftp-root=/srv/tftpboot

# UEFI x64 clients (option 93 = 7)
dhcp-match=set:efi-x86_64,option:client-arch,7
dhcp-boot=tag:efi-x86_64,shimx64.efi

# BIOS clients (option 93 = 0) - fallback
dhcp-match=set:bios,option:client-arch,0
dhcp-boot=tag:bios,pxelinux.0

# Log DHCP queries
log-dhcp
DNSEOF

# nginx - serves only kickstart file, blank for everything else
cat > /etc/nginx/conf.d/kickstart.conf <<'NGINXEOF'
server {
    listen 80 default_server;
    server_name _;

    location = /kickstart/ks.cfg {
        root /var/www;
        default_type text/plain;
    }

    location / {
        return 204;
    }
}
NGINXEOF

rm -f /etc/nginx/conf.d/default.conf

# Skeleton client kickstart
mkdir -p /var/www/kickstart
cat > /var/www/kickstart/ks.cfg <<CLIENTKSEOF
# Client kickstart - served by pxehost
# AlmaLinux 9 minimal install

text
reboot

url --url="${ALMA_INST_REPO}"

lang en_US.UTF-8
keyboard us
timezone UTC --utc

network --bootproto=dhcp --onboot=yes

rootpw --lock

user --name=rootbruker00 --groups=wheel --lock
sshkey --username=rootbruker00 "${PUBKEY}"

zerombr
clearpart --all --initlabel
autopart --type=lvm --nohome

selinux --enforcing

%packages --ignoremissing
@^minimal-environment
bash-completion
curl
%end

%post
cat > /etc/sudoers.d/rootbruker00 <<'EOF'
rootbruker00 ALL=(ALL) NOPASSWD: ALL
EOF
chmod 0440 /etc/sudoers.d/rootbruker00
%end
CLIENTKSEOF

chmod 644 /var/www/kickstart/ks.cfg

# Firewall
firewall-cmd --permanent --add-service=dhcp
firewall-cmd --permanent --add-service=tftp
firewall-cmd --permanent --add-service=http
firewall-cmd --reload

# SELinux context for TFTP root
semanage fcontext -a -t tftpdir_rw_t '/srv/tftpboot(/.*)?'
restorecon -Rv /srv/tftpboot

# Start services
systemctl enable --now dnsmasq
systemctl enable --now nginx

%end
KSEOF

    log "VM kickstart written."
}

# ---------------------------------------------------------------------------
# Step 5: Run virt-install
# Kickstart injected directly into installer initrd - no HTTP server needed
# ---------------------------------------------------------------------------
run_virt_install() {
    log "Creating VM disk at $VM_DISK_PATH..."
    qemu-img create -f qcow2 "$VM_DISK_PATH" "${VM_DISK_GB}G"

    local ks_basename
    ks_basename=$(basename "$KS_FILE")

    log "Starting virt-install..."

    virt-install \
        --name "$VM_NAME" \
        --vcpus "$VM_VCPUS" \
        --memory "$VM_RAM_MB" \
        --disk "path=${VM_DISK_PATH},format=qcow2,bus=virtio" \
        --network "bridge=${BRIDGE},model=virtio" \
        --location "$ALMA_ISO_PATH" \
        --initrd-inject "$KS_FILE" \
        --extra-args "inst.ks=file://${ks_basename} inst.repo=${ALMA_INST_REPO} console=tty0 console=ttyS0,115200n8" \
        --os-variant almalinux9 \
        --graphics none \
        --console pty,target_type=serial \
        --boot uefi \
        --noautoconsole \
        --wait -1

    log "VM installation complete."
}

# ---------------------------------------------------------------------------
# Cleanup
# ---------------------------------------------------------------------------
cleanup() {
    [[ -f "$KS_FILE" ]] && rm -f "$KS_FILE"
}

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
[[ "$(id -u)" -ne 0 ]] && die "Must run as root"

require virt-install qemu-img nmcli ip ping curl firewall-cmd semanage

trap cleanup EXIT

find_or_create_bridge
find_free_ip
fetch_iso
write_vm_kickstart
run_virt_install

log "Done. PXE host VM '${VM_NAME}' is running at ${VM_IP}"
log "  TFTP root:  /srv/tftpboot"
log "  Kickstart:  http://${VM_IP}/kickstart/ks.cfg"
log "  dnsmasq:    proxy DHCP + TFTP on ${SUBNET}.0/${PREFIX}"
